feat: ready for review
VlaPol/TMS_Lesson_13 pull request #1
Opened 2023-02-20 16:10 UTC by VlaPol

2023-02-21 18:43 UTC, oleg-grigorijan requested changes

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +    public IntList() {
Тут лучше проинициализировать arrayList пустым массивом и убрать все проверки на null дальше

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +
Можно было использовать Arrays.toString(...), но ладно

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        if (arrayList == null || arrayList.length == 0) {
Пустота списка не является ошибкой. Ошибкой будет указание несуществующего индекса. Да, для пустого массива массива любой индекс будет несуществующий, но ошибка та же.

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        }
Зачем тут цикл. Как мы можем обратиться к элементу массива по индексу?

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        }
Опять же зачем тут цикл. Как мы можем присвоить значение элементу массива по индексу?

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        }
А как тогда работать с IntList, который был создан через конструктор без аргументов?

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        }
Нет смысла в проверке. new int[arrayList.length + 1] отработает корректно и для нулевой длины

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        }
Ок, но можно написать проще через два вызова System.arraycopy(...)

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +
Нет перегруженного subList с одним параметром

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +            newList.add(arrayList[i]);
Очень дорогая реализация. Каждый вызов add – это создание нового массива в памяти. Можно написать проще и эффективнее через вызов Arrays.copyOfRange(…) или System.arraycopy(...)

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        if (arrayList == null || arrayList.length == 0) {
Пустота списка тут не ошибка. Просто элемент в любом случае будет не найден, вернётся -1

2023-02-21 18:43 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        if (arrayList == null || arrayList.length == 0) {
Пустота списка тут не ошибка. Отсортированный пустой список – это пустой список

2023-02-21 18:56 UTC, VlaPol commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        }
Даа, что-то я тут действительно перемудрил

2023-02-21 19:05 UTC, VlaPol commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        if (arrayList == null || arrayList.length == 0) {
Изменил.

2023-02-21 19:06 UTC, VlaPol commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +    public IntList() {
Изменил

2023-02-21 19:06 UTC, VlaPol commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        if (arrayList == null || arrayList.length == 0) {
Исправил

2023-02-21 19:06 UTC, VlaPol commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        }
Исправил

2023-02-21 19:08 UTC, VlaPol commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        if (arrayList == null || arrayList.length == 0) {
Согласен, исправил.

2023-02-21 19:09 UTC, VlaPol commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        }
Согласен, исправил.

2023-02-21 19:13 UTC, VlaPol commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +
Упс, я пропустил этот таск. Добавил

2023-02-21 19:49 UTC, VlaPol commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +            newList.add(arrayList[i]);
Согласен, изменил

2023-02-22 05:56 UTC, oleg-grigorijan requested changes

2023-02-22 05:56 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +    public IntList() {
Инициализацию в данном случае лучше сделать внутри конструктора. Иначе изначально в IntList(int[]) будет выделена память под пустой массив тоже

2023-02-22 05:56 UTC, oleg-grigorijan commented on src/by/tms/lesson13/homework/myarraylist/IntList.java
> +        return new IntList(tmpArray);
Дублирование кода. Реализуй через вызов существующего subList(int, int)

2023-02-22 06:18 UTC, oleg-grigorijan approved these changes

2023-02-22 14:30 UTC, merged